interface types {
    use jabratech:common/types.{currency};
    record request{
        currency: currency,
        date: option<string>,
    }

    record fit{
        name: string,
        value: f64,
    }

    record fit-response{
        code: s16,
        message: string,
        data: list<fit>,
    }

    record fit-data{
        maturity: string,
        atm: f64,
        weight: f64,
        interpolator-vol: f64,
        fit-weight: f64,
    }

    record fit-data-response{
        code: s16,
        message: string,
        data: list<fit-data>,
    }


    record fit-graph{
        x: list<string>,
        y-interpolator-vol: list<f64>,
        y-atm: list<f64>,
    }

    record fit-graph-response{
        code: s16,
        message: string,
        data: fit-graph,
    }

}